version: v1.0
fail_fast: true
plan: standard-2

paths:
  - app/**
  - bin/**
  - config/**
  - db/**
  - lib/**
  - test/**
  - .neetoci/default.yml
  - .neetoci/scripts/run_eslint_on_modified_files.sh
  - .neetoci/scripts/run_rubocop_and_erblint_on_modified_files.sh
  - .neetoci/scripts/check_schema_drift.sh
  - Gemfile*
  - package.json
  - yarn.lock
  - Rakefile
  - .env.test
  - config.ru
  - .*.yml
  - .ruby-version
  - .node-version
  - .nvmrc
  - .active_record_doctor.rb
  - .prettierrc.js
  - "*.config.*"
  - .eslintignore
  - .eslintrc.js

commands:
  - checkout
  - neetoci-version node 22.13
  - cache restore
  - yarn install
  - cache store
  - yarn build
  - bash .neetoci/scripts/check_links.sh
  - bash .neetoci/scripts/validate_bundled.sh

triggers:
  - event: pull_request
